[build]
  publish = "dist"
  command = "npx yarn --cwd menu-footer copy && npm run generate && npm run export"

[[headers]]
  for = "/_nuxt/*"

  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''